### ISSUE TITLE
OpenGL_ES 2 support?

### ISSUE THREAD

**Issue by vanfanel** [duganchen/dosbox#13]
Hi, dugan!

I have tried building this on the Raspberry Pi, and only output=surface seems to work (which uses SDL2 GLES2 renderer under the hood, I suppose).
So, my question is: could you add OpenGL_ES2 support? (SDL2 can initialize GLES2 context with no problems, not only full desktop GL). The Raspberry's GPU is capable of simple scanlines shaders, etc...

Also, using output=surface I get the dosbox screen on a small area on the center of the screen: it should be stretched to the full "window" (there's no window on the Pi, since SDL2 programs run fullscreen, directly usingthe native 2D api as a 2D subsystem). Using software scalers is a waste of CPU on this platform, as GLES2 scaling is CPU-free.

**Comment by duganchen** [comment]
I can't promise to do anything more than "look into it" at this time, but I'll gladly accept a community pull request as long as the changes aren't too intrusive.

I'm a bit surprised to hear that output=texture and output=texturenb (which are OpenGL-backed) aren't working on the pi though.

**Comment by vanfanel** [comment]
@duganchen : Ah, it works after all! It was just a matter of setting fullscreen=true.
There's no windowing system as such on the Pi (well, there's X, but who uses X on the Pi?? SDL2 runs GREAT directly on dispamx or KMS/DRM!!), so sdlmain.cpp must be trying to create a window and failing, and fullscreen=true makes it work.
Well, your can close this issue, or I can do it. Your fork DOES work on the Pi with GL (GLES2 to be precise) throught SDL2.
No need to fix anything regarding this issue.
Thanks! :+1:

**Comment by duganchen** [comment]
Oh, very nice! Thanks for the update.
