### ISSUE TITLE
A question about shaders

### ISSUE THREAD

**Issue by vanfanel** [duganchen/dosbox#19]
Hi,

I am enjoying this dosbox fork a lot these days, but I was wondering why shaders don't work here.
I have scanline.vert and scanline.frag living on the shaders subdir (it's a subir of the dir where my.conf is), and I have set:

```
output=texture
gl.shader=scanline
texture.renderer=auto

```

I have also tried copying the "shaders" dir to ~/.dosbox, where the default .conf lives, but it makes no difference. 

However the shader does not seem to be loaded. Any ideas on what could I be doing wrong?

**Comment by duganchen** [comment]
Shaders only work with "output=opengl" or "output=openglnb". That's documented in ENHANCEMENTS.md.

**Comment by duganchen** [comment]
ENHANCEMENT.md is now README.md. It should be less missable now.
