### ISSUE TITLE
Combining pixel shaders ?

### ISSUE THREAD

**Issue by bidinou** [duganchen/dosbox#24]
Hi ! 
First : thanks so much for this dosbox fork !! :-)

As a RetroArch user, I grew to enjoy shaders quite a lot.

I managed to get them to work under dosbox, however, is it possible to chain / combine shaders as it's possible under RetroArch ?

For instance, I literally love the result of the combination of an xbrz shader (scaled 3 times for instance) with crt-lottes. It's absolutely stunning IMHO. Is is possible to do it with your dosbox fork ?

I can provide an example of the result (obtained in RetroArch).

Cheers !

**Comment by duganchen** [comment]
Nope.

This fork only supports single-pass shaders.

Sorry.

**Comment by duganchen** [comment]
And no, I don't need RetroArch shaders explained to me. Running RetroArch shaders in DosBox was what motivated this project in the first place, the shader format is directly based (by me) on RetroArch's Cg format, and most of the available shaders were converted from RetroArch's by me.

**Comment by bidinou** [comment]
No problem, thanks for replying ! 
Best regards
