### ISSUE TITLE
[Improvement / Update] Update to 0.74-2 / r4156

### ISSUE THREAD

**Issue by 5schatten** [duganchen/dosbox#25]
Well I was wondering if you have any plans to update your fork to 0.74-2 / r4156?

https://sourceforge.net/p/dosbox/code-0/4156/

**Comment by duganchen** [comment]
Yes. I've just been distracted with other things lately.

**Comment by 5schatten** [comment]
btw. if you find time to look into the code, maybe you could you adept this GLES stuff too? Since a lot of SBC systems are powerful enough to run Dosbox it would be great to have some nice shading effects around.

https://github.com/aqualung99/dosbox-0.74-ES

**Comment by duganchen** [comment]
Sorry, no. I'm a desktop gamer myself, and I'm not the one to be doing anything with GLES.

You might, however, suggest *them* to incorporate the shading effects from this fork.

**Comment by 5schatten** [comment]
No problem, I'm fine without some scanlines ;-)

**Comment by Tkcmd** [comment]
Duganchen are you still working on this and going to publish an updated version?

**Comment by duganchen** [comment]
I’m busy with other things right now, but I’m good for testing and merging
updates if you want to submit one.

**Comment by Tkcmd** [comment]
I'll look into it but am afraid that this will surpass my current knowledge and skills.

**Comment by duganchen** [comment]
Fixed with https://github.com/duganchen/dosbox/pull/27
