### ISSUE TITLE
emscripten support

### ISSUE THREAD

**Issue by kyr0** [duganchen/dosbox#28]
Hi dugan :)

great fork! Thank you for your work. I'm porting many of my old games to Google Chrome using emscripten (em-dosbox with custom enhancements). I noticed that em-dosbox has issues with GLES using SDL2. But I read here:

    https://github.com/duganchen/dosbox/issues/13

That GLES is indeed supported when using SDL2. As I read, emscripten should compile the GLES to WebGL when compiling with certain flags:

    https://emscripten.org/docs/porting/multimedia_and_graphics/OpenGL-support.html
    https://emscripten.org/docs/optimizing/Optimizing-WebGL.html

I'm not very experienced with emscripten and my C/C++ skills are a bit dusted but I guess I could quick & dirty patch this fork with support for emscripten. 

Do you think it would work with WebGL like I hope?
Would you welcome a PR like this? 

From my point of view it would be just amazing to be able to play all those games in high speed just by visiting a website :)

Atm. most of my games are already running well in the browser (including mounted CD images, CD music and videos, MIDI etc.). It required to use the most recent emscripten and WebAssembly features :) But for "perfect" GL support would be needed :)

Thanks in advance!

**Comment by duganchen** [comment]
That's a really cool idea, but I'd prefer if you do it in your own fork and not submit a pull request
