### ISSUE TITLE
Update to DOSBox 0.74-3

### ISSUE THREAD

**Issue by 5schatten** [duganchen/dosbox#29]
@moralrecordings 
Do you have some time to spare for this update too? We much appreciate your efforts! :+1: 
https://www.dosbox.com/DOSBoxManual.html

**Comment by duganchen** [comment]
I'm not going to say no, but I'm also going to have to say "not soon".
If anyone wants to do it themselves, it would be easiest to backport the following patches:
https://www.vogons.org/viewtopic.php?f=41&t=43068&start=20#p568163

**Comment by duganchen** [comment]
Merged the pull request :)
https://github.com/duganchen/dosbox/pull/30
