### ISSUE TITLE
Can't mount ISO with compressed audio track

### ISSUE THREAD

**Issue by escalade** [duganchen/dosbox#4]
It seems like SDL_sound is needed to mount ISO images using imgmount, is that right? Works fine in the regular SDL version. Any way to add this?

**Comment by duganchen** [comment]
A _bit_ more information would be nice...
1. What makes you suspect that SDL_sound is the problem? Is it specified in the error message that you obviously should have posted but didn't? Was there something in the source code that made you determine that? Or did you just do a web search for the error you got (that again, you should have posted) and then get forum posters saying "build with SDL_sound"?
2. How representative is this discussion to what you're talking about? Are you having trouble mounting ISOs or are you having trouble mounting cue sheets with both data and CD tracks? 

http://www.linuxquestions.org/questions/slackware-14/cannot-mount-cue-images-in-dosbox-0-74-a-4175421232/

**Comment by escalade** [comment]
Sorry, should have been more detailed :)
1. I suspected SDL_sound because it was a mixed mode ISO and had read somewhere that it was a requirement.
2. It's 100% representative, and actually gave me an idea how to solve my issue. The ISO I was trying to mount came from GOG.com and had an OGG compressed audio track. Someone in the thread you linked mentioned that SDL_sound was required for compressed tracks, so I converted the OGG track to WAV and what do you know it works :)

I'll leave this open but feel free to close it if you don't care about this feature.

PS: Great work, this fork works well on both x86_64 and arm/RPi3!

Thanks!

**Comment by duganchen** [comment]
I don't mean to ignore this point. I dropped SDL_sound support because DosBox can't confirm that SDL_sound was actually built against SDL2. Details here:

http://www.vogons.org/viewtopic.php?f=32&t=34770&start=40#p462629

I've had another look, and I now see that the obvious solution is to add SDL_sound to the source tree. I'm going to look into that.

**Comment by Glog78** [comment]
any news on that might be probably a problem with the MM 4-5 CD version from gog

**Comment by duganchen** [comment]
What's "MM 4-5"?

**Comment by duganchen** [comment]
I've restored SDL_Sound support. To make it work properly you'll have to first build SDL_Sound against SDL2 (or install a version that's built against SDL2), and then build DosBox against it.

This is really the best I can do.

**Comment by Glog78** [comment]
Hi duganchen it was a little of a fight to find a working solution but i think i found one you might even include into your build. http://hg.icculus.org/icculus/SDL_sound (hg repository) now builds a libSDL2_sound. This one works as far as i checked MM5 CD Version. Maybe including this one into the build is an idea to avoid the build using SDL_sound which still (default on arch for example) is linked against SDL1.
