### ISSUE TITLE
Doesn't compile with openglide

### ISSUE THREAD

**Issue by Glog78** [duganchen/dosbox#7]
The current git doesn't compile against openglide. I supose its because of openglide depends on SDL.

g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I/usr/include/openglide/ -I/usr/include/SDL2 -D_REENTRANT  -g -O2 -mno-ms-bitfields  -MT glide.o -MD -MP -MF .deps/glide.Tpo -c -o glide.o glide.cpp
glide.cpp: In function 'void GLIDE_ResetScreen(bool)':
glide.cpp:518:24: error: 'SDL_FULLSCREEN' was not declared in this scope
   (glide.fullscreen[0]?SDL_FULLSCREEN:0)|SDL_ANYFORMAT|SDL_SWSURFACE);
                        ^~~~~~~~~~~~~~
glide.cpp:518:42: error: 'SDL_ANYFORMAT' was not declared in this scope
   (glide.fullscreen[0]?SDL_FULLSCREEN:0)|SDL_ANYFORMAT|SDL_SWSURFACE);
                                          ^~~~~~~~~~~~~
glide.cpp:518:69: error: 'SDL_SetVideoMode' was not declared in this scope
   (glide.fullscreen[0]?SDL_FULLSCREEN:0)|SDL_ANYFORMAT|SDL_SWSURFACE);
                                                                     ^
glide.cpp: In constructor 'GLIDE::GLIDE(Section*)':
glide.cpp:396:50: warning: ignoring return value of 'size_t fread(void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Wunused-result]
      fread(ovl_data, sizeof(char), ovl_size, ovl);

**Comment by duganchen** [comment]
Please report this to the SDL2 development thread on Vogons. 

http://www.vogons.org/viewtopic.php?t=34770
