### ISSUE TITLE
Incorrectly tries to include glew when compiling for RPi

### ISSUE THREAD

**Issue by escalade** [duganchen/dosbox#9]
In src/Makefile.am libs/glew-2.0.0/glew.c is added regardless whether or not OpenGL is enabled. This fails on RPi as there isn'ẗ any OpenGL libraries/headers (GL/glu.h).

Perhaps make it configurable as --enable-glew?

**Comment by duganchen** [comment]
I've updated the master branch with an attempt to fix this. Let me know if it works.

The change:

https://github.com/duganchen/dosbox/commit/50114b6482e679ce7dcafacd1671b5db21247641

**Comment by duganchen** [comment]
Looks like it worked. I just successfully built it with --disable-opengl.

**Comment by duganchen** [comment]
Reverted. That doesn't work if you do build with OpenGL. Will have to work on this a bit more.

**Comment by duganchen** [comment]
K it's fixed again.

The commit:

https://github.com/duganchen/dosbox/commit/1427002f7274c93256729f7367c6d17d22c5d814
